name: GitHub Pages - Generate XML sitemap

# Trigger the workflow manually or on a schedule (every day at midnight)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
      # Step to harden the runner for security purposes
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      # Step to checkout the repository
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      # Step to generate the sitemap using the cicirello/generate-sitemap action
      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@eb8db82126ee30619883c8c43e8c49ec14ebd6dc # v1.10.1
        with:
          base-url-path: https://recycling.typpi.online/
          additional-extensions: doc docx ppt pptx js css json xml xlsx xls pdf md markdown txt lua yaml yml png

      # Step to output the sitemap generation stats for debugging and verification
      - name: Output stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      # Step to create a pull request with the new sitemap
      - name: Create Pull Request with new SiteMap
        id: create_pr
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          title: "Automated sitemap update"
          body: >
            Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap)
            GitHub action. Automated pull-request generated by the
            [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.

      # Step to set the pull request number or ID as an environment variable
      - name: Set pull request number or ID
        id: set_pr_number
        run: |
          pr_number=$(gh pr list --state open --base main --json number -q '.[0].number')
          if [ -n "$pr_number" ]; then
            echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
          else
            echo "PR_NUMBER=" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step to enable auto-merge for the pull request if the actor is 'Nick2bad4u'
      - name: Enable Pull Request Automerge
        if: github.actor == 'Nick2bad4u' && env.PR_NUMBER != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ env.PR_NUMBER }}
          merge-method: squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step to merge the pull request automatically using the GitHub CLI
      - name: Merge Pull Request
        if: github.actor == 'Nick2bad4u' && env.PR_NUMBER != ''
        run: |
          gh pr merge -R "Nick2bad4u/Recycling4.0-Fixed" --squash --auto "${{ env.PR_NUMBER }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional step to list notifications for debugging
      - name: List Notifications
        if: github.actor == 'Nick2bad4u'
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/notifications
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step to mark notifications as read
      - name: Mark Notification as Read
        if: github.actor == 'Nick2bad4u'
        run: |
          response=$(curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/notifications \
            -d '{"last_read_at":"'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'","read":true}')

          echo "API Response: $response"
          status_code=$(echo $response | jq -r '.status')

          if [ "$status_code" -eq 202 ]; then
            echo "Notifications are being marked as read in the background."
          elif [ "$status_code" -eq 205 ]; then
            echo "All notifications have been marked as read."
          else
            echo "Failed to mark notifications as read. Response: $response"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
